services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: skill-sync-backend-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - skillsync-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-server:
    image: eclipse-temurin:17-jre-alpine
    container_name: discovery-server
    ports:
      - "8761:8761"
    volumes:
      - ./discovery-server/target:/app
    command: ["sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app/discovery-server-1.0.0*.jar"]
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - skillsync-network

  api-gateway:
    image: eclipse-temurin:17-jre-alpine
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/target:/app
    command: ["sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app/api-gateway-1.0.0*.jar"]
    env_file: .env
    environment:
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID=true
    depends_on:
      - discovery-server
    networks:
      - skillsync-network

  user-service:
    image: eclipse-temurin:17-jre-alpine
    container_name: user-service
    ports:
      - "8082:8082"
    volumes:
      - ./user-service/target:/app
    command: [ "sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app/user-service-1.0.0*.jar" ]
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/skillsync_user?createDatabaseIfNotExist=true
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      rabbitmq:
        condition: service_healthy
      discovery-server:
        condition: service_started
    networks:
      - skillsync-network


  auth-service:
    image: eclipse-temurin:17-jre-alpine
    container_name: auth-service
    ports:
      - "8081:8081"
    volumes:
      - ./auth-service/target:/app
    command: ["sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /app/auth-service-1.0.0*.jar"]
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/skillsync_auth?createDatabaseIfNotExist=true
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - USER_SERVICE_URL=http://user-service:8082
      - RABBITMQ_HOST=rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      rabbitmq:
        condition: service_healthy
      discovery-server:
        condition: service_started
    networks:
      - skillsync-network


networks:
  skillsync-network:
    driver: bridge
