global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "skillsync-services"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - discovery-server:8761
          - api-gateway:8080
          - auth-service:8081
          - user-service:8082
          - skill-service:8083
          - mentor-service:8084
          - session-service:8085
          - group-service:8086
          - review-service:8087
          - notification-service:8088
