server.port=8888
spring.application.name=config-server

# Git backend — SSH config repo
spring.cloud.config.server.git.uri=${CONFIG_GIT_URI:git@github.com:SubodhKatna/skillsync-confi.git}
spring.cloud.config.server.git.default-label=${CONFIG_GIT_BRANCH:main}
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.strict-host-key-checking=false

# Eureka registration
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

management.endpoints.web.exposure.include=health,info,refresh
management.endpoint.health.show-details=always
